BlackTimber-Labs/Portfolio-Website

html/Ravi Gupta.html

Create Ravi Gupta.html

---

css/style.css

Made changes to navigation bar to make the website look more appealing

Made navbar rounded

---

html/Dinesh9350.html

customized and edit the content of the portfolio website.

Dinesh9350.html added

---

html/dsasaank-369.css
html/dsasaank-369.html

Converted the given photoshop design to code

Cloned the Portfolio website

---

html/nithu2109.css
html/nithu2109.html

Replicated the given design to code

adding both html and css files

---

html/surya-doc.html

Created my own portfolio with my details.

Added Surya's portfolio

---

html/shelendravashishtha2.html

Hacktober Submission

---

css/Meheer-shukla.css
html/Meheer-Shukla.html

My Portfolio

---

css/apurv.css
html/Apurv.html

Made several css and content changes in the Portfolio Website

Made my Portfolio Website

---

css/normal_vj.css
css/style_vj.css
html/Vivan_Jaiswal_profile.html

Added my profile [Vivan Jaiswal css and html]

---

Aditya rana Portfolio/Readme.md

I have only created the Readme file  in my portfolio folder where i have attached the link of my Portfolio website

Aditya rana portfolio

---

Srivari's Portfolio/app.js
Srivari's Portfolio/index.html
Srivari's Portfolio/style.css

Added Srivari's Portfolio

---

Satyam's Portfolio/CSS/style.css
Satyam's Portfolio/HTML/satyam1906.html

I have made some changes in index.html file and uploading it here as my portfolio

Made some suitable changes in index.html

---

html/abc.html

Added a new portfolio website in html directory

Added my portfolio website

---

html/sandeep.html

sandeepPortfolio

---

Personal Portfolio/Kieran's website/k.krug.html

This is my web page. Starter webpage, I'll work on it throughout my university career.

My website page

---

html/schenker.html

Created Schenker portfolio page

---

Personal Portfolio/Abhishek's Portfolio/index.html
Personal Portfolio/Abhishek's Portfolio/style.css

I have added a static Portfolio Website built using HTML and CSS.

Added Abhishek's Portfolio Website

---

html/Ashutosh.html

Hello Portfolio added under the guidelines. Please accept under hacktoberfest'22 label

Portfolio Added

---

html/index.html

This is a portfolio website, @RITEKROUNAK kindly review my PR under hacktoberfest2022.

Sarthak Portfolio

---

html/AdityaMore7000.html

Added my html file in html directory.
Dear Maintainer, kindly accept this PR and add the hacktoberfest-accepted label to this PR.
Thank you for giving me an opportunity to contribute to your repository

added AdityaMore7000.html

---

html/Rahul-Learner.html

Added Saw-Industries Portfolio.😊😊😊😊

---

Personal Portfolio/Himanshu's Portfolio/index.html
Personal Portfolio/Himanshu's Portfolio/normal.css
Personal Portfolio/Himanshu's Portfolio/reset.css
Personal Portfolio/Himanshu's Portfolio/style.css

I have added my portfolio website codes to this repo.
Language used: HTML and CSS

Portfolio website has been committed

---

Personal Portfolio/Hidesec Portfolio/css/style.css
Personal Portfolio/Hidesec Portfolio/cv/portfolio.html
Personal Portfolio/Hidesec Portfolio/index.html

Please Review change:
- Add Hidesec Portfolio
File changes:
- ```Personal Portfolio/Hidesec Portfolio/css/style.css```
- ```Personal Portfolio/Hidesec Portfolio/cv/portfolio.html```
- ```Personal Portfolio/Hidesec Portfolio/index.html```

Adding hidesec Portfolio

---

html/PushpitSahay.html

Added Portfolio page using HTML.

---

html/Martin.html

Created Portfolio using template

Martin-Mohobo.html
